#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

foreach (['TMP', 'TEMP'] as $tempVariable) {
    putenv($tempVariable.'=C:\\laragon\\tmp');
    $_ENV[$tempVariable] = 'C:\\laragon\\tmp';
    $_SERVER[$tempVariable] = 'C:\\laragon\\tmp';
}

require __DIR__.'/bootstrap/polyfills.php';

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
